# Setup
name:             Kathryn Renée Thomas
title:            "Kathryn Renée Thomas"
tagline:          "Writer, Actor, Katydid, Executive Producer"
description:      "Official website of Kathryn Renée Thomas, writer, actor and executive producer in Los Angeles."
paginate:         5
url:              "http://kathrynreneethomas.github.io" # the base hostname & protocol for your site
baseurl:          "" # the subpath of your site, e.g. /blog/
canonical:        "http://kathrynreneethomas.com"
keywords:         "Kathryn Renée Thomas, Katie Thomas, Katydids, Teachers TV Land, Katydids Improv"

# Permalinks
permalink: /:title
relative_permalinks: true


# Build settings
markdown: kramdown
include: [".htaccess"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
#  style:            :compressed


# Navigation
nav:
  - title: Hire Me
    url: /hire-me/
  - title: About
    url: /about/
  - title: Teachers
    url: /teachers/
  - title: Press
    url: /press/
  - title: Media
    url: /media/
  - title: Contact
    url: /contact/


# About / Contact
authors:
  katie:
    name: Kathryn Renée Thomas
    bio:  Kathryn Renée Thomas (Katie) is a writer and actor in Los Angeles. She is a member of the Katydids and a creator and star of Teachers on TV Land.

    url:              http://kathrynreneethomas.com
    email:            kathrynrenee@gmail.com
    twitter_username: mskathrynrenee
    img:              http://placehold.it/300


# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "katie"
      layout: "post"
      category: articles
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" #
    values:
      layout: "page"

# Custom Vars
version:            1.0
github:
  repo: